// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCCIJL_pDutlhqwLGKaMasqeG3dEa53xw',
    appId: '1:560246898308:android:1f5f2718a91f88d86d0cd1',
    messagingSenderId: '560246898308',
    projectId: 'ecommerce-app-38948',
    storageBucket: 'ecommerce-app-38948.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3J7GMHYMoQpQziF-6Prg3BmLCOgoTKuc',
    appId: '1:560246898308:ios:069c22836dda41a66d0cd1',
    messagingSenderId: '560246898308',
    projectId: 'ecommerce-app-38948',
    storageBucket: 'ecommerce-app-38948.firebasestorage.app',
    androidClientId: '560246898308-gsh7j0pfj0q3iop2i95vf4ehatuu8dh2.apps.googleusercontent.com',
    iosClientId: '560246898308-7jc3nv4fb51dl7e05gaifmpabun83a0a.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

}